const refs = {
  headerRef: document.querySelector('.header'),
  movieListRef: document.querySelector('.movies-list'),
  navigationRef: document.querySelector('.navigation'),
  logoRef: document.querySelector('.navigation-logo'),
  homeRef: document.querySelector('.navigation-home'),
  homeLinkRef: document.querySelector('.navigation-home-link'),
  myLibraryRef: document.querySelector('.navigation-my-library'),
  myLibraryLinkRef: document.querySelector('.navigation-my-library-link'),
  searchFormRef: document.querySelector('.search-form'),
  errorMessageRef: document.querySelector('.error-message'),
  paginationRef: document.querySelector('.pagination'),
  modalRef: document.querySelector('.js-modal'),
  bodyRef: document.querySelector('body'),
  btnWatchedRef: document.querySelector('.btn-watched'),
  btnQueueRef: document.querySelector('.btn-queue'),
  btnsMyLibrary: document.querySelector('.my-library-buttons'),
  btnAddWatched: document.querySelector('.btn-add-watched'),
  btnAddQueue: document.querySelector('.btn-add-queue'),
};
export default refs;
